version: '3.4'

services:
  internxt-core.public.dappnode.eth:
    build: ./build
    restart: always
    volumes:
      - 'internxt_core_config:/root/.xcore'
    ports:
      - '45555:45555'
    environment:
      - INXT=0x0123456789012345678901234567890123456789
      - SIZE=50GB
      - RPC_PORT=45555
      - RPC_ADDRESS=45.45.45.45
    image: 'internxt-core.public.dappnode.eth:1.0.0'

volumes:
  internxt_core_config: {}
